### ISSUE TITLE
License ..?

### ISSUE THREAD

**Issue by sri-soham** [jeremytubbs/deepzoom#10]
Hello,

Can you please add a license file to the repository? Without a license, it will be difficult for others to use this library.
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

Regards,
Sridhar

**Comment by jeremytubbs** [comment]
MIT - https://github.com/jeremytubbs/deepzoom/blob/master/composer.json#L4
