### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by meeximum** [jeremytubbs/deepzoom#4]
Hi Jeremy,

sorry but it seem's I'm to dump to get this running in my ubuntu system :-(
I cloned the repo and run compose install, it creates a vendor dir with all dependencies, but when I try to make a default implementation as you mentioned, I get a 500 error :-/
My root directory has a src dir with your code, a vendor dir with dependencies, I create a index.php with the code you mentioned on your site?

regards
Meex

**Comment by jeremytubbs** [comment]
Meex,

How familiar are you with working with composer packages? 
https://getcomposer.org/doc/01-basic-usage.md#autoloading

You may just need to add this line:
```PHP
require __DIR__ . '/vendor/autoload.php';
```

**Comment by meeximum** [comment]
Perfect, I missed the require statement!

best regards
Meex
