### ISSUE TITLE
How to plug this plug-in - what is needed additionally?

### ISSUE THREAD

**Issue by Medwar** [jeremytubbs/deepzoom#6]
I am trying to plug
https://github.com/jeremytubbs/deepzoom
into my PHP project (to create tiles and DZIs on server side after each image is loaded).

Contrary to the plugins I've been using previosly, this one seem not to contain every library it refers to, and there's neither description nor examples of joining any additional files in the readme.
I will appreciate any advice on how to make it work.

Currently I don't know what to do with this in DeepzoomFactory.php:
use InvalidArgumentException;
use Intervention\Image\ImageManager;
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;

Does it mean that I have to download each of these libraries ( Intervention Image, League Flysystem) additionaly and place each of them into separate folder? I tried to do so, but it still doesn't work.
Do I have to include every ".php" file from this libraries into DeepZoom.php? Seems like I am on the wrong way and missing something about importing namespaces.

Best Regards,
Pavel.

**Comment by jeremytubbs** [comment]
The project uses a dependency mamangement tool for PHP called Composer. Read the documentation on how to get started at - https://getcomposer.org/doc/00-intro.md

**Comment by jeremytubbs** [comment]
Also refer to issue #4 as it also concerns composer installation.

**Comment by differenceclouds** [comment]
Hi, this snagged me as well. i am admittedly new to this, but maybe a change in the documentation to make this more clear would save people like me time in the future? Just a line about the composer setup would be great. thanks!
