### ISSUE TITLE
no decode delegate for this image format `SVS'

### ISSUE THREAD

**Issue by Frankling** [jeremytubbs/deepzoom#8]
no decode delegate for this image format `SVS'

**Comment by jeremytubbs** [comment]
Never heard of this format before, thanks for the knowledge. Maybe support could be added if I create a new package that utilizes libvips.

 http://paulbourke.net/dataformats/svs/

**Comment by sha-N** [comment]
Hi, sorry to reopen a closed issue. @jeremytubbs you have mentioned libvips in last comment, is there a plan for implementing that, looks like it performs much better than imagick, like to hear your thoughts on it.

**Comment by jeremytubbs** [comment]
> Hi, sorry to reopen a closed issue. @jeremytubbs you have mentioned libvips in last comment, is there a plan for implementing that, looks like it performs much better than imagick, like to hear your thoughts on it.

I would suggest using javascript, https://github.com/lovell/sharp directly it has a very quick and simple `tile` output option.
