### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire()

### ISSUE THREAD

**Issue by clydesantiago** [jeremytubbs/deepzoom#9]
The fire method (which was deprecated in Laravel 5.4) of the Illuminate/Events/Dispatcher class has been removed <laravel/framework#26392>. You should use the dispatch method instead in <https://github.com/jeremytubbs/deepzoom/blob/master/src/Deepzoom.php>.

**Comment by jeremytubbs** [comment]
Just tagged a new release 0.6.0 which addresses this issue. Thanks for reporting!
